config/routes.rb
Rails.application.routes.draw do
  resources :todos do
    member do
      patch :complete
    end
  end
  root to: "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  scope :complete, ->{ where.not(completed_at: nil) }
  scope :incomplete, ->{ where(completed_at: nil) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :complete]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.order(completed_at: :desc, created_at: :asc)
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_path }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def complete
    @todo.update(completed_at: @todo.completed_at? ? nil : Time.zone.now)
    respond_to do |format|
      format.html { redirect_to todos_path }
      format.json { render :show, status: :ok, location: @todo }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:description, :completed_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
  def todo_class(todo)
    "completed" if todo.completed_at?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Personal Todo List</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.4/js/tether.min.js', 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-light bg-white">
      <div class="container">
        <a class="navbar-brand" href="/">
          Heroku CI/CD Example 2
        </a>
      </div>
    </nav>


    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for(todo) do |f| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :completed_at %>
    <%= f.datetime_select :completed_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<div class="jumbotron">
  <%= form_for Todo.new do |f| %>
    <div class="form-group mr-2">
      <%= f.text_field :description, placeholder: "Add a new todo...", autofocus: true, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Add this todo", class: "btn btn-primary" %>
      <button type="reset" value="reset" class="btn btn-secondary">Cancel</button>

    </div>
  <% end %>

  <br />

  <div>
    <h5><%= Todo.complete.count %> / <%= Todo.all.count %> Complete</h5>
    <hr />

    <% @todos.each do |todo| %>
      <div id="<%= dom_id(todo) %>" class="<%= todo_class(todo) %>">
        <%= form_for todo, url: complete_todo_path(todo) do |f| %>
          <div class="form-check">
            <label class="custom-control custom-checkbox">
              <%= f.check_box :completed_at, checked: todo.completed_at?, class: "custom-control-input" %>
              <span class="custom-control-indicator"></span>
              <span class="custom-control-description"><%= todo.description %></span>
              <%= link_to fa_icon("times"), todo, method: :delete, class: "text-light ml-2" %>
            </label>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @todo.description %>
</p>

<p>
  <strong>Completed at:</strong>
  <%= @todo.completed_at %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>